### ISSUE TITLE
Handling pytest 3.1

### ISSUE THREAD

**Issue by The-Compiler** [fschulze/pytest-warnings#9]
In pytest 3.1 (to be released), pytest-warnings has been merged into the core. However, if the plugin is still installed, this happens:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../site-packages/pytest.py", line 73, in <module>
    raise SystemExit(pytest.main())
  File ".../site-packages/_pytest/config.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File ".../site-packages/_pytest/config.py", line 158, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File ".../site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File ".../site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File ".../site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File ".../site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File ".../site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File ".../site-packages/_pytest/helpconfig.py", line 34, in pytest_cmdline_parse
    config = outcome.get_result()
  File ".../site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File ".../site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File ".../site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File ".../site-packages/_pytest/config.py", line 928, in pytest_cmdline_parse
    self.parse(args)
  File ".../site-packages/_pytest/config.py", line 1086, in parse
    self._preparse(args, addopts=addopts)
  File ".../site-packages/_pytest/config.py", line 1048, in _preparse
    self.pluginmanager.load_setuptools_entrypoints(entrypoint_name)
  File ".../site-packages/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File ".../site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File ".../site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File ".../site-packages/pytest_warnings/__init__.py", line 1, in <module>
    from _pytest.recwarn import RecordedWarning, WarningsRecorder
ImportError: cannot import name 'RecordedWarning'
```

Not sure what would be best to do in this case. Show a warning from pytest-warnings (hah) telling people to uninstall it?

cc @nicoddemus

**Comment by RonnyPfannschmidt** [comment]
we can instruct pytest 3.1 to block the plugin  for example?

**Comment by fschulze** [comment]
> we can instruct pytest 3.1 to block the plugin for example?

If that is possible with a note that the plugin is now included, we should go for that.

**Comment by RonnyPfannschmidt** [comment]
@fschulze a more easy way would be to check in the plugin itself at pytest_configure time, or use the import failure as reason to skip the rest

**Comment by fschulze** [comment]
I'm fine with either way, whatever is easier.

**Comment by nicoddemus** [comment]
I would prefer to make a change in pytest-warning itself rather than in pytest: changing the plugin is just a matter of making a new pytest-warnings release, while doing the change in pytest means we would have to keep that change around "forever" as we don't know when people would actually uninstall pytest-warnings.

@RonnyPfannschmidt what was done when pytest-core was integrated into pytest?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus for pytest-cache we just disabled the plugin from inside pytest

**Comment by nicoddemus** [comment]
Can you point me to the code that does that? A quick glance at `cacheprovider` didn't turn out anything for me.
